# Generated by Django 5.1.5 on 2025-01-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Status code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.orderstatus',
                verbose_name='Order status'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(verbose_name='Table number'),
        ),
    ]
