# Generated by Django 5.1.5 on 2025-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderstatus_alter_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list, verbose_name='Items list'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
